
<table>
	<tr>
		<th>#</th>
		<th>Firstname</th>
		<th>Lastname</th>
		<th><a href="/application/user/add" class="btn btn-default">Add user</a></th>
	</tr>
	<?php foreach ($users as $user): ?>
	<tr>
		<td><?= $user->getId(); ?></td>
		<td><?= $user->getFirstname(); ?></td>
		<td><?= $user->getLastname(); ?></td>
		<td><a href="/application/user/edit/<?= $user->getId(); ?>" class="btn btn-default" title="Edit user">edit</a></td>
	</tr>
	<?php endforeach; ?>
</table>
